### ISSUE TITLE
Require Linux/ARM64 docker image for lareeth/alpine-ci-tools 

### ISSUE THREAD

**Issue by odidev** [lareeth/alpine-ci-tools#9]
Hi Team, 

I worked on building lareeth/alpine-ci-tools images for both AMD64 and ARM64 platforms and faced issues on both. Hence, I have modified the dockerfile to resolve the issues for the amd64 platform and made it compatible with arm64 platform as well. 

Successfully built and tested the lareeth/alpine-ci-tools image over AMD64 and ARM64 platforms after the changes. 

Modified the .travis.yml file and added support to release images on dockerhub for both the platforms. 

**Modified files:** https://github.com/odidev/alpine-ci-tools/commit/d198351a74018b1b281f04b400da22e5fe9ef1b0 

Do you have any plans for releasing arm64 images? 

It will be very helpful if an arm64 image is available. If interested, I will raise a PR.

**Comment by lareeth** [comment]
Can you raise a PR for this? LGTM

**Comment by lareeth** [comment]
I have implemented this using BuildKit instead of building using travis arm64 builders. Have a look at the error from the build in https://github.com/lareeth/alpine-ci-tools/pull/12 as this shows some issues with the python install on arm

**Comment by lareeth** [comment]
ARM64 images are now available
